### ISSUE TITLE
How to get the missing models?

### ISSUE THREAD

**Issue by wenxuanxie** [wision-lab/eventful-transformer#1]
Hi there, thank you for sharing the code. It is super helpful!

While I am able to run the basic configurations, I find some other configurations require the following models. Do you know how to acquire them?

- `weights/vivit_b_kinetics400_final_24.pth`
- `weights/vivit_b_kinetics400_final_48.pth`
- `weights/vivit_b_kinetics400_final_96.pth`
- `weights/vivit_b_epic_kitchens_final_50.pth`
- `weights/vivit_b_epic_kitchens_final_100.pth`
- `weights/vivit_b_epic_kitchens_final_200.pth`

**Comment by mattdutson** [comment]
Hi! Here's a link to those weights: https://drive.google.com/drive/folders/1AP-NRhO4l_spEJ6ZXvfVO3PLlLOsXCmM?usp=sharing

If you wanted, you could also obtain these weights but running a `spatial` configuration, followed by the corresponding `train` configuration to fine-tune the ViViT temporal model. For example:
```
./scripts/spatial/vivit_epic_kitchens.py ./configs/spatial/vivit_epic_kitchens/50.yml
```
followed by
```
./scripts/train/vivit_epic_kitchens.py ./configs/train/vivit_epic_kitchens/final_50.yml
```
