### ISSUE TITLE
Argument mismatch

### ISSUE THREAD

**Issue by wenxuanxie** [wision-lab/eventful-transformer#2]
There is an argument mismatch while calling `ViViTPreprocessing`. Seems to be unintended?

In [Line80@models/vivit.py](https://github.com/WISION-Lab/eventful-transformer/blob/bc0774a1c2a9fbc18644a39373dd7df2a811ca4b/models/vivit.py#L80) it looks like

```
self.preprocessing = ViViTPreprocessing(
    input_shape,
    normalize_mean,
    normalize_std,
    temporal_stride,
    temporal_views,
    **spatial_views,**
)
 ```

while in [Line201@models/vivit.py](https://github.com/WISION-Lab/eventful-transformer/blob/bc0774a1c2a9fbc18644a39373dd7df2a811ca4b/models/vivit.py#L201) it is

```
def __init__(
    self,
    input_shape,
    normalize_mean,
    normalize_std,
    **spatial_views,**
    temporal_stride,
    temporal_views,
):
```

**Comment by mattdutson** [comment]
Thanks for pointing this out - I just pushed a fix.

Good news: I checked the Git blame and it looks like the inconsistent argument ordering was only introduced recently (last month) while I was adding docstrings. This was after I ran experiments for the paper. So, if you re-run the evaluation scripts with this new fix you should get results consistent with the paper.
